

rocketmq:
  name-server: 117.50.68.180:9876


example:
#  name-server: 117.50.68.180:9876
  rocketmq:
    topic: string-topic
    order-topic: order-paid-topic
    msg-ext-topic: message-ext-topic
    trans-topic: transaction-topic
    order-paid-consumer: spring-transaction-topic

spring:
  application:
    name: example-consume
