server:
  port: 9823
  servlet:
    context-path: study

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.id.new_generator_mappings: false
      hibernate.dialect.storage_engine: innodb
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
