server:
  port: 9823
  servlet:
    context-path: study

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: sa
    password: sa
    url: jdbc:h2:mem:dbtest
    platform: h2
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.id.new_generator_mappings: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy



  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
