// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signalling-message.proto

package com.netty.example.server.proto;

public final class SignallingMessage {
  private SignallingMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * Protobuf enum {@code com.netty.example.server.proto.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *数据
     * </pre>
     *
     * <code>DATA = 1;</code>
     */
    DATA(1),
    /**
     * <pre>
     *信令
     * </pre>
     *
     * <code>SIGNALLING = 2;</code>
     */
    SIGNALLING(2),
    ;

    /**
     * <pre>
     *数据
     * </pre>
     *
     * <code>DATA = 1;</code>
     */
    public static final int DATA_VALUE = 1;
    /**
     * <pre>
     *信令
     * </pre>
     *
     * <code>SIGNALLING = 2;</code>
     */
    public static final int SIGNALLING_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 1: return DATA;
        case 2: return SIGNALLING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.netty.example.server.proto.SignallingMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.netty.example.server.proto.MessageType)
  }

  public interface WrapperMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.netty.example.server.proto.WrapperMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *过期时间，-1表示不过期
     * </pre>
     *
     * <code>required int64 expireTimes = 2;</code>
     */
    boolean hasExpireTimes();
    /**
     * <pre>
     *过期时间，-1表示不过期
     * </pre>
     *
     * <code>required int64 expireTimes = 2;</code>
     */
    long getExpireTimes();

    /**
     * <pre>
     *优先级
     * </pre>
     *
     * <code>required int32 priority = 3;</code>
     */
    boolean hasPriority();
    /**
     * <pre>
     *优先级
     * </pre>
     *
     * <code>required int32 priority = 3;</code>
     */
    int getPriority();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.netty.example.server.proto.MessageType type = 4;</code>
     */
    boolean hasType();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.netty.example.server.proto.MessageType type = 4;</code>
     */
    com.netty.example.server.proto.SignallingMessage.MessageType getType();

    /**
     * <pre>
     *是否加密
     * </pre>
     *
     * <code>required bool isEncryption = 5;</code>
     */
    boolean hasIsEncryption();
    /**
     * <pre>
     *是否加密
     * </pre>
     *
     * <code>required bool isEncryption = 5;</code>
     */
    boolean getIsEncryption();

    /**
     * <pre>
     *是否需要ack
     * </pre>
     *
     * <code>required bool needAck = 6;</code>
     */
    boolean hasNeedAck();
    /**
     * <pre>
     *是否需要ack
     * </pre>
     *
     * <code>required bool needAck = 6;</code>
     */
    boolean getNeedAck();

    /**
     * <pre>
     *消息的数据类型
     * </pre>
     *
     * <code>required string payloadType = 7;</code>
     */
    boolean hasPayloadType();
    /**
     * <pre>
     *消息的数据类型
     * </pre>
     *
     * <code>required string payloadType = 7;</code>
     */
    java.lang.String getPayloadType();
    /**
     * <pre>
     *消息的数据类型
     * </pre>
     *
     * <code>required string payloadType = 7;</code>
     */
    com.google.protobuf.ByteString
        getPayloadTypeBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required bytes payload = 8;</code>
     */
    boolean hasPayload();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required bytes payload = 8;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <pre>
     *消息来源
     * </pre>
     *
     * <code>required string referer = 9;</code>
     */
    boolean hasReferer();
    /**
     * <pre>
     *消息来源
     * </pre>
     *
     * <code>required string referer = 9;</code>
     */
    java.lang.String getReferer();
    /**
     * <pre>
     *消息来源
     * </pre>
     *
     * <code>required string referer = 9;</code>
     */
    com.google.protobuf.ByteString
        getRefererBytes();
  }
  /**
   * <pre>
   *消息
   * </pre>
   *
   * Protobuf type {@code com.netty.example.server.proto.WrapperMessage}
   */
  public  static final class WrapperMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.netty.example.server.proto.WrapperMessage)
      WrapperMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WrapperMessage.newBuilder() to construct.
    private WrapperMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WrapperMessage() {
      id_ = 0L;
      expireTimes_ = 0L;
      priority_ = 0;
      type_ = 1;
      isEncryption_ = false;
      needAck_ = false;
      payloadType_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
      referer_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WrapperMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              expireTimes_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              priority_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.netty.example.server.proto.SignallingMessage.MessageType value = com.netty.example.server.proto.SignallingMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = rawValue;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isEncryption_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              needAck_ = input.readBool();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              payloadType_ = bs;
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              payload_ = input.readBytes();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              referer_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_WrapperMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_WrapperMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.example.server.proto.SignallingMessage.WrapperMessage.class, com.netty.example.server.proto.SignallingMessage.WrapperMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int EXPIRETIMES_FIELD_NUMBER = 2;
    private long expireTimes_;
    /**
     * <pre>
     *过期时间，-1表示不过期
     * </pre>
     *
     * <code>required int64 expireTimes = 2;</code>
     */
    public boolean hasExpireTimes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *过期时间，-1表示不过期
     * </pre>
     *
     * <code>required int64 expireTimes = 2;</code>
     */
    public long getExpireTimes() {
      return expireTimes_;
    }

    public static final int PRIORITY_FIELD_NUMBER = 3;
    private int priority_;
    /**
     * <pre>
     *优先级
     * </pre>
     *
     * <code>required int32 priority = 3;</code>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *优先级
     * </pre>
     *
     * <code>required int32 priority = 3;</code>
     */
    public int getPriority() {
      return priority_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.netty.example.server.proto.MessageType type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.netty.example.server.proto.MessageType type = 4;</code>
     */
    public com.netty.example.server.proto.SignallingMessage.MessageType getType() {
      com.netty.example.server.proto.SignallingMessage.MessageType result = com.netty.example.server.proto.SignallingMessage.MessageType.valueOf(type_);
      return result == null ? com.netty.example.server.proto.SignallingMessage.MessageType.DATA : result;
    }

    public static final int ISENCRYPTION_FIELD_NUMBER = 5;
    private boolean isEncryption_;
    /**
     * <pre>
     *是否加密
     * </pre>
     *
     * <code>required bool isEncryption = 5;</code>
     */
    public boolean hasIsEncryption() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *是否加密
     * </pre>
     *
     * <code>required bool isEncryption = 5;</code>
     */
    public boolean getIsEncryption() {
      return isEncryption_;
    }

    public static final int NEEDACK_FIELD_NUMBER = 6;
    private boolean needAck_;
    /**
     * <pre>
     *是否需要ack
     * </pre>
     *
     * <code>required bool needAck = 6;</code>
     */
    public boolean hasNeedAck() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *是否需要ack
     * </pre>
     *
     * <code>required bool needAck = 6;</code>
     */
    public boolean getNeedAck() {
      return needAck_;
    }

    public static final int PAYLOADTYPE_FIELD_NUMBER = 7;
    private volatile java.lang.Object payloadType_;
    /**
     * <pre>
     *消息的数据类型
     * </pre>
     *
     * <code>required string payloadType = 7;</code>
     */
    public boolean hasPayloadType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *消息的数据类型
     * </pre>
     *
     * <code>required string payloadType = 7;</code>
     */
    public java.lang.String getPayloadType() {
      java.lang.Object ref = payloadType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          payloadType_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息的数据类型
     * </pre>
     *
     * <code>required string payloadType = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadTypeBytes() {
      java.lang.Object ref = payloadType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payloadType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString payload_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required bytes payload = 8;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required bytes payload = 8;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int REFERER_FIELD_NUMBER = 9;
    private volatile java.lang.Object referer_;
    /**
     * <pre>
     *消息来源
     * </pre>
     *
     * <code>required string referer = 9;</code>
     */
    public boolean hasReferer() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     *消息来源
     * </pre>
     *
     * <code>required string referer = 9;</code>
     */
    public java.lang.String getReferer() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          referer_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息来源
     * </pre>
     *
     * <code>required string referer = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRefererBytes() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExpireTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsEncryption()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNeedAck()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayloadType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReferer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, expireTimes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, priority_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isEncryption_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, needAck_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, payloadType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, payload_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, referer_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, expireTimes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, priority_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isEncryption_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, needAck_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, payloadType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, payload_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, referer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netty.example.server.proto.SignallingMessage.WrapperMessage)) {
        return super.equals(obj);
      }
      com.netty.example.server.proto.SignallingMessage.WrapperMessage other = (com.netty.example.server.proto.SignallingMessage.WrapperMessage) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasExpireTimes() == other.hasExpireTimes());
      if (hasExpireTimes()) {
        result = result && (getExpireTimes()
            == other.getExpireTimes());
      }
      result = result && (hasPriority() == other.hasPriority());
      if (hasPriority()) {
        result = result && (getPriority()
            == other.getPriority());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasIsEncryption() == other.hasIsEncryption());
      if (hasIsEncryption()) {
        result = result && (getIsEncryption()
            == other.getIsEncryption());
      }
      result = result && (hasNeedAck() == other.hasNeedAck());
      if (hasNeedAck()) {
        result = result && (getNeedAck()
            == other.getNeedAck());
      }
      result = result && (hasPayloadType() == other.hasPayloadType());
      if (hasPayloadType()) {
        result = result && getPayloadType()
            .equals(other.getPayloadType());
      }
      result = result && (hasPayload() == other.hasPayload());
      if (hasPayload()) {
        result = result && getPayload()
            .equals(other.getPayload());
      }
      result = result && (hasReferer() == other.hasReferer());
      if (hasReferer()) {
        result = result && getReferer()
            .equals(other.getReferer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasExpireTimes()) {
        hash = (37 * hash) + EXPIRETIMES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getExpireTimes());
      }
      if (hasPriority()) {
        hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + getPriority();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasIsEncryption()) {
        hash = (37 * hash) + ISENCRYPTION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsEncryption());
      }
      if (hasNeedAck()) {
        hash = (37 * hash) + NEEDACK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNeedAck());
      }
      if (hasPayloadType()) {
        hash = (37 * hash) + PAYLOADTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getPayloadType().hashCode();
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      if (hasReferer()) {
        hash = (37 * hash) + REFERER_FIELD_NUMBER;
        hash = (53 * hash) + getReferer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netty.example.server.proto.SignallingMessage.WrapperMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *消息
     * </pre>
     *
     * Protobuf type {@code com.netty.example.server.proto.WrapperMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.netty.example.server.proto.WrapperMessage)
        com.netty.example.server.proto.SignallingMessage.WrapperMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_WrapperMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_WrapperMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.example.server.proto.SignallingMessage.WrapperMessage.class, com.netty.example.server.proto.SignallingMessage.WrapperMessage.Builder.class);
      }

      // Construct using com.netty.example.server.proto.SignallingMessage.WrapperMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        expireTimes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        priority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000008);
        isEncryption_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        needAck_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        payloadType_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        referer_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_WrapperMessage_descriptor;
      }

      public com.netty.example.server.proto.SignallingMessage.WrapperMessage getDefaultInstanceForType() {
        return com.netty.example.server.proto.SignallingMessage.WrapperMessage.getDefaultInstance();
      }

      public com.netty.example.server.proto.SignallingMessage.WrapperMessage build() {
        com.netty.example.server.proto.SignallingMessage.WrapperMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netty.example.server.proto.SignallingMessage.WrapperMessage buildPartial() {
        com.netty.example.server.proto.SignallingMessage.WrapperMessage result = new com.netty.example.server.proto.SignallingMessage.WrapperMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.expireTimes_ = expireTimes_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isEncryption_ = isEncryption_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.needAck_ = needAck_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.payloadType_ = payloadType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.referer_ = referer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.example.server.proto.SignallingMessage.WrapperMessage) {
          return mergeFrom((com.netty.example.server.proto.SignallingMessage.WrapperMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.example.server.proto.SignallingMessage.WrapperMessage other) {
        if (other == com.netty.example.server.proto.SignallingMessage.WrapperMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasExpireTimes()) {
          setExpireTimes(other.getExpireTimes());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasIsEncryption()) {
          setIsEncryption(other.getIsEncryption());
        }
        if (other.hasNeedAck()) {
          setNeedAck(other.getNeedAck());
        }
        if (other.hasPayloadType()) {
          bitField0_ |= 0x00000040;
          payloadType_ = other.payloadType_;
          onChanged();
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasReferer()) {
          bitField0_ |= 0x00000100;
          referer_ = other.referer_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasExpireTimes()) {
          return false;
        }
        if (!hasPriority()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasIsEncryption()) {
          return false;
        }
        if (!hasNeedAck()) {
          return false;
        }
        if (!hasPayloadType()) {
          return false;
        }
        if (!hasPayload()) {
          return false;
        }
        if (!hasReferer()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.example.server.proto.SignallingMessage.WrapperMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.example.server.proto.SignallingMessage.WrapperMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long expireTimes_ ;
      /**
       * <pre>
       *过期时间，-1表示不过期
       * </pre>
       *
       * <code>required int64 expireTimes = 2;</code>
       */
      public boolean hasExpireTimes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *过期时间，-1表示不过期
       * </pre>
       *
       * <code>required int64 expireTimes = 2;</code>
       */
      public long getExpireTimes() {
        return expireTimes_;
      }
      /**
       * <pre>
       *过期时间，-1表示不过期
       * </pre>
       *
       * <code>required int64 expireTimes = 2;</code>
       */
      public Builder setExpireTimes(long value) {
        bitField0_ |= 0x00000002;
        expireTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *过期时间，-1表示不过期
       * </pre>
       *
       * <code>required int64 expireTimes = 2;</code>
       */
      public Builder clearExpireTimes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        expireTimes_ = 0L;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <pre>
       *优先级
       * </pre>
       *
       * <code>required int32 priority = 3;</code>
       */
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *优先级
       * </pre>
       *
       * <code>required int32 priority = 3;</code>
       */
      public int getPriority() {
        return priority_;
      }
      /**
       * <pre>
       *优先级
       * </pre>
       *
       * <code>required int32 priority = 3;</code>
       */
      public Builder setPriority(int value) {
        bitField0_ |= 0x00000004;
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *优先级
       * </pre>
       *
       * <code>required int32 priority = 3;</code>
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000004);
        priority_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 1;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.netty.example.server.proto.MessageType type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.netty.example.server.proto.MessageType type = 4;</code>
       */
      public com.netty.example.server.proto.SignallingMessage.MessageType getType() {
        com.netty.example.server.proto.SignallingMessage.MessageType result = com.netty.example.server.proto.SignallingMessage.MessageType.valueOf(type_);
        return result == null ? com.netty.example.server.proto.SignallingMessage.MessageType.DATA : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.netty.example.server.proto.MessageType type = 4;</code>
       */
      public Builder setType(com.netty.example.server.proto.SignallingMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.netty.example.server.proto.MessageType type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 1;
        onChanged();
        return this;
      }

      private boolean isEncryption_ ;
      /**
       * <pre>
       *是否加密
       * </pre>
       *
       * <code>required bool isEncryption = 5;</code>
       */
      public boolean hasIsEncryption() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *是否加密
       * </pre>
       *
       * <code>required bool isEncryption = 5;</code>
       */
      public boolean getIsEncryption() {
        return isEncryption_;
      }
      /**
       * <pre>
       *是否加密
       * </pre>
       *
       * <code>required bool isEncryption = 5;</code>
       */
      public Builder setIsEncryption(boolean value) {
        bitField0_ |= 0x00000010;
        isEncryption_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否加密
       * </pre>
       *
       * <code>required bool isEncryption = 5;</code>
       */
      public Builder clearIsEncryption() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isEncryption_ = false;
        onChanged();
        return this;
      }

      private boolean needAck_ ;
      /**
       * <pre>
       *是否需要ack
       * </pre>
       *
       * <code>required bool needAck = 6;</code>
       */
      public boolean hasNeedAck() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *是否需要ack
       * </pre>
       *
       * <code>required bool needAck = 6;</code>
       */
      public boolean getNeedAck() {
        return needAck_;
      }
      /**
       * <pre>
       *是否需要ack
       * </pre>
       *
       * <code>required bool needAck = 6;</code>
       */
      public Builder setNeedAck(boolean value) {
        bitField0_ |= 0x00000020;
        needAck_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否需要ack
       * </pre>
       *
       * <code>required bool needAck = 6;</code>
       */
      public Builder clearNeedAck() {
        bitField0_ = (bitField0_ & ~0x00000020);
        needAck_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object payloadType_ = "";
      /**
       * <pre>
       *消息的数据类型
       * </pre>
       *
       * <code>required string payloadType = 7;</code>
       */
      public boolean hasPayloadType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *消息的数据类型
       * </pre>
       *
       * <code>required string payloadType = 7;</code>
       */
      public java.lang.String getPayloadType() {
        java.lang.Object ref = payloadType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            payloadType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息的数据类型
       * </pre>
       *
       * <code>required string payloadType = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadTypeBytes() {
        java.lang.Object ref = payloadType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payloadType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息的数据类型
       * </pre>
       *
       * <code>required string payloadType = 7;</code>
       */
      public Builder setPayloadType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        payloadType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息的数据类型
       * </pre>
       *
       * <code>required string payloadType = 7;</code>
       */
      public Builder clearPayloadType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        payloadType_ = getDefaultInstance().getPayloadType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息的数据类型
       * </pre>
       *
       * <code>required string payloadType = 7;</code>
       */
      public Builder setPayloadTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        payloadType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required bytes payload = 8;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required bytes payload = 8;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required bytes payload = 8;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required bytes payload = 8;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000080);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private java.lang.Object referer_ = "";
      /**
       * <pre>
       *消息来源
       * </pre>
       *
       * <code>required string referer = 9;</code>
       */
      public boolean hasReferer() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       *消息来源
       * </pre>
       *
       * <code>required string referer = 9;</code>
       */
      public java.lang.String getReferer() {
        java.lang.Object ref = referer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            referer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息来源
       * </pre>
       *
       * <code>required string referer = 9;</code>
       */
      public com.google.protobuf.ByteString
          getRefererBytes() {
        java.lang.Object ref = referer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息来源
       * </pre>
       *
       * <code>required string referer = 9;</code>
       */
      public Builder setReferer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        referer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息来源
       * </pre>
       *
       * <code>required string referer = 9;</code>
       */
      public Builder clearReferer() {
        bitField0_ = (bitField0_ & ~0x00000100);
        referer_ = getDefaultInstance().getReferer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息来源
       * </pre>
       *
       * <code>required string referer = 9;</code>
       */
      public Builder setRefererBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        referer_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.netty.example.server.proto.WrapperMessage)
    }

    // @@protoc_insertion_point(class_scope:com.netty.example.server.proto.WrapperMessage)
    private static final com.netty.example.server.proto.SignallingMessage.WrapperMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netty.example.server.proto.SignallingMessage.WrapperMessage();
    }

    public static com.netty.example.server.proto.SignallingMessage.WrapperMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WrapperMessage>
        PARSER = new com.google.protobuf.AbstractParser<WrapperMessage>() {
      public WrapperMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WrapperMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WrapperMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WrapperMessage> getParserForType() {
      return PARSER;
    }

    public com.netty.example.server.proto.SignallingMessage.WrapperMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConnectionMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.netty.example.server.proto.ConnectionMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *会话标识
     * </pre>
     *
     * <code>required string sessionIdentifier = 1;</code>
     */
    boolean hasSessionIdentifier();
    /**
     * <pre>
     *会话标识
     * </pre>
     *
     * <code>required string sessionIdentifier = 1;</code>
     */
    java.lang.String getSessionIdentifier();
    /**
     * <pre>
     *会话标识
     * </pre>
     *
     * <code>required string sessionIdentifier = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdentifierBytes();
  }
  /**
   * <pre>
   *连接消息
   * </pre>
   *
   * Protobuf type {@code com.netty.example.server.proto.ConnectionMessage}
   */
  public  static final class ConnectionMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.netty.example.server.proto.ConnectionMessage)
      ConnectionMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConnectionMessage.newBuilder() to construct.
    private ConnectionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectionMessage() {
      sessionIdentifier_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConnectionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sessionIdentifier_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_ConnectionMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_ConnectionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.example.server.proto.SignallingMessage.ConnectionMessage.class, com.netty.example.server.proto.SignallingMessage.ConnectionMessage.Builder.class);
    }

    private int bitField0_;
    public static final int SESSIONIDENTIFIER_FIELD_NUMBER = 1;
    private volatile java.lang.Object sessionIdentifier_;
    /**
     * <pre>
     *会话标识
     * </pre>
     *
     * <code>required string sessionIdentifier = 1;</code>
     */
    public boolean hasSessionIdentifier() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *会话标识
     * </pre>
     *
     * <code>required string sessionIdentifier = 1;</code>
     */
    public java.lang.String getSessionIdentifier() {
      java.lang.Object ref = sessionIdentifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionIdentifier_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *会话标识
     * </pre>
     *
     * <code>required string sessionIdentifier = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdentifierBytes() {
      java.lang.Object ref = sessionIdentifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionIdentifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSessionIdentifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionIdentifier_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionIdentifier_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netty.example.server.proto.SignallingMessage.ConnectionMessage)) {
        return super.equals(obj);
      }
      com.netty.example.server.proto.SignallingMessage.ConnectionMessage other = (com.netty.example.server.proto.SignallingMessage.ConnectionMessage) obj;

      boolean result = true;
      result = result && (hasSessionIdentifier() == other.hasSessionIdentifier());
      if (hasSessionIdentifier()) {
        result = result && getSessionIdentifier()
            .equals(other.getSessionIdentifier());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSessionIdentifier()) {
        hash = (37 * hash) + SESSIONIDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getSessionIdentifier().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netty.example.server.proto.SignallingMessage.ConnectionMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *连接消息
     * </pre>
     *
     * Protobuf type {@code com.netty.example.server.proto.ConnectionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.netty.example.server.proto.ConnectionMessage)
        com.netty.example.server.proto.SignallingMessage.ConnectionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_ConnectionMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_ConnectionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.example.server.proto.SignallingMessage.ConnectionMessage.class, com.netty.example.server.proto.SignallingMessage.ConnectionMessage.Builder.class);
      }

      // Construct using com.netty.example.server.proto.SignallingMessage.ConnectionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sessionIdentifier_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.example.server.proto.SignallingMessage.internal_static_com_netty_example_server_proto_ConnectionMessage_descriptor;
      }

      public com.netty.example.server.proto.SignallingMessage.ConnectionMessage getDefaultInstanceForType() {
        return com.netty.example.server.proto.SignallingMessage.ConnectionMessage.getDefaultInstance();
      }

      public com.netty.example.server.proto.SignallingMessage.ConnectionMessage build() {
        com.netty.example.server.proto.SignallingMessage.ConnectionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netty.example.server.proto.SignallingMessage.ConnectionMessage buildPartial() {
        com.netty.example.server.proto.SignallingMessage.ConnectionMessage result = new com.netty.example.server.proto.SignallingMessage.ConnectionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessionIdentifier_ = sessionIdentifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.example.server.proto.SignallingMessage.ConnectionMessage) {
          return mergeFrom((com.netty.example.server.proto.SignallingMessage.ConnectionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.example.server.proto.SignallingMessage.ConnectionMessage other) {
        if (other == com.netty.example.server.proto.SignallingMessage.ConnectionMessage.getDefaultInstance()) return this;
        if (other.hasSessionIdentifier()) {
          bitField0_ |= 0x00000001;
          sessionIdentifier_ = other.sessionIdentifier_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSessionIdentifier()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.example.server.proto.SignallingMessage.ConnectionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.example.server.proto.SignallingMessage.ConnectionMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sessionIdentifier_ = "";
      /**
       * <pre>
       *会话标识
       * </pre>
       *
       * <code>required string sessionIdentifier = 1;</code>
       */
      public boolean hasSessionIdentifier() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *会话标识
       * </pre>
       *
       * <code>required string sessionIdentifier = 1;</code>
       */
      public java.lang.String getSessionIdentifier() {
        java.lang.Object ref = sessionIdentifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sessionIdentifier_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *会话标识
       * </pre>
       *
       * <code>required string sessionIdentifier = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdentifierBytes() {
        java.lang.Object ref = sessionIdentifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionIdentifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *会话标识
       * </pre>
       *
       * <code>required string sessionIdentifier = 1;</code>
       */
      public Builder setSessionIdentifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话标识
       * </pre>
       *
       * <code>required string sessionIdentifier = 1;</code>
       */
      public Builder clearSessionIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionIdentifier_ = getDefaultInstance().getSessionIdentifier();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话标识
       * </pre>
       *
       * <code>required string sessionIdentifier = 1;</code>
       */
      public Builder setSessionIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionIdentifier_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.netty.example.server.proto.ConnectionMessage)
    }

    // @@protoc_insertion_point(class_scope:com.netty.example.server.proto.ConnectionMessage)
    private static final com.netty.example.server.proto.SignallingMessage.ConnectionMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netty.example.server.proto.SignallingMessage.ConnectionMessage();
    }

    public static com.netty.example.server.proto.SignallingMessage.ConnectionMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ConnectionMessage>
        PARSER = new com.google.protobuf.AbstractParser<ConnectionMessage>() {
      public ConnectionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConnectionMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectionMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectionMessage> getParserForType() {
      return PARSER;
    }

    public com.netty.example.server.proto.SignallingMessage.ConnectionMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_example_server_proto_WrapperMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_example_server_proto_WrapperMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_example_server_proto_ConnectionMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_example_server_proto_ConnectionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030signalling-message.proto\022\036com.netty.ex" +
      "ample.server.proto\032\031google/protobuf/any." +
      "proto\"\334\001\n\016WrapperMessage\022\n\n\002id\030\001 \002(\003\022\023\n\013" +
      "expireTimes\030\002 \002(\003\022\020\n\010priority\030\003 \002(\005\0229\n\004t" +
      "ype\030\004 \002(\0162+.com.netty.example.server.pro" +
      "to.MessageType\022\024\n\014isEncryption\030\005 \002(\010\022\017\n\007" +
      "needAck\030\006 \002(\010\022\023\n\013payloadType\030\007 \002(\t\022\017\n\007pa" +
      "yload\030\010 \002(\014\022\017\n\007referer\030\t \002(\t\".\n\021Connecti" +
      "onMessage\022\031\n\021sessionIdentifier\030\001 \002(\t*\'\n\013" +
      "MessageType\022\010\n\004DATA\020\001\022\016\n\nSIGNALLING\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_com_netty_example_server_proto_WrapperMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_netty_example_server_proto_WrapperMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_example_server_proto_WrapperMessage_descriptor,
        new java.lang.String[] { "Id", "ExpireTimes", "Priority", "Type", "IsEncryption", "NeedAck", "PayloadType", "Payload", "Referer", });
    internal_static_com_netty_example_server_proto_ConnectionMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_netty_example_server_proto_ConnectionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_example_server_proto_ConnectionMessage_descriptor,
        new java.lang.String[] { "SessionIdentifier", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
