// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task-message.proto

package com.netty.example.server.proto;

public final class TaskMessageOuterClass {
  private TaskMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.netty.example.server.proto.ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *新任务
     * </pre>
     *
     * <code>NEW = 1;</code>
     */
    NEW(1),
    /**
     * <pre>
     *启动任务
     * </pre>
     *
     * <code>START = 2;</code>
     */
    START(2),
    /**
     * <pre>
     *停止任务
     * </pre>
     *
     * <code>STOP = 3;</code>
     */
    STOP(3),
    /**
     * <pre>
     *移除任务
     * </pre>
     *
     * <code>REMOVE = 6;</code>
     */
    REMOVE(6),
    /**
     * <pre>
     *更新任务
     * </pre>
     *
     * <code>UPDATE = 7;</code>
     */
    UPDATE(7),
    ;

    /**
     * <pre>
     *新任务
     * </pre>
     *
     * <code>NEW = 1;</code>
     */
    public static final int NEW_VALUE = 1;
    /**
     * <pre>
     *启动任务
     * </pre>
     *
     * <code>START = 2;</code>
     */
    public static final int START_VALUE = 2;
    /**
     * <pre>
     *停止任务
     * </pre>
     *
     * <code>STOP = 3;</code>
     */
    public static final int STOP_VALUE = 3;
    /**
     * <pre>
     *移除任务
     * </pre>
     *
     * <code>REMOVE = 6;</code>
     */
    public static final int REMOVE_VALUE = 6;
    /**
     * <pre>
     *更新任务
     * </pre>
     *
     * <code>UPDATE = 7;</code>
     */
    public static final int UPDATE_VALUE = 7;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    public static ActionType forNumber(int value) {
      switch (value) {
        case 1: return NEW;
        case 2: return START;
        case 3: return STOP;
        case 6: return REMOVE;
        case 7: return UPDATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.netty.example.server.proto.TaskMessageOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.netty.example.server.proto.ActionType)
  }

  public interface TaskMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.netty.example.server.proto.TaskMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *目标设备
     * </pre>
     *
     * <code>required string target = 1;</code>
     */
    boolean hasTarget();
    /**
     * <pre>
     *目标设备
     * </pre>
     *
     * <code>required string target = 1;</code>
     */
    java.lang.String getTarget();
    /**
     * <pre>
     *目标设备
     * </pre>
     *
     * <code>required string target = 1;</code>
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <pre>
     *动作类型
     * </pre>
     *
     * <code>required .com.netty.example.server.proto.ActionType actionType = 2;</code>
     */
    boolean hasActionType();
    /**
     * <pre>
     *动作类型
     * </pre>
     *
     * <code>required .com.netty.example.server.proto.ActionType actionType = 2;</code>
     */
    com.netty.example.server.proto.TaskMessageOuterClass.ActionType getActionType();

    /**
     * <pre>
     *任务id 列表
     * </pre>
     *
     * <code>repeated int64 taskIds = 3;</code>
     */
    java.util.List<java.lang.Long> getTaskIdsList();
    /**
     * <pre>
     *任务id 列表
     * </pre>
     *
     * <code>repeated int64 taskIds = 3;</code>
     */
    int getTaskIdsCount();
    /**
     * <pre>
     *任务id 列表
     * </pre>
     *
     * <code>repeated int64 taskIds = 3;</code>
     */
    long getTaskIds(int index);
  }
  /**
   * <pre>
   *任务消息
   * </pre>
   *
   * Protobuf type {@code com.netty.example.server.proto.TaskMessage}
   */
  public  static final class TaskMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.netty.example.server.proto.TaskMessage)
      TaskMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskMessage.newBuilder() to construct.
    private TaskMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskMessage() {
      target_ = "";
      actionType_ = 1;
      taskIds_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              target_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.netty.example.server.proto.TaskMessageOuterClass.ActionType value = com.netty.example.server.proto.TaskMessageOuterClass.ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                actionType_ = rawValue;
              }
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                taskIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              taskIds_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                taskIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                taskIds_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          taskIds_ = java.util.Collections.unmodifiableList(taskIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.example.server.proto.TaskMessageOuterClass.internal_static_com_netty_example_server_proto_TaskMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.example.server.proto.TaskMessageOuterClass.internal_static_com_netty_example_server_proto_TaskMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage.class, com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage.Builder.class);
    }

    private int bitField0_;
    public static final int TARGET_FIELD_NUMBER = 1;
    private volatile java.lang.Object target_;
    /**
     * <pre>
     *目标设备
     * </pre>
     *
     * <code>required string target = 1;</code>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *目标设备
     * </pre>
     *
     * <code>required string target = 1;</code>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *目标设备
     * </pre>
     *
     * <code>required string target = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIONTYPE_FIELD_NUMBER = 2;
    private int actionType_;
    /**
     * <pre>
     *动作类型
     * </pre>
     *
     * <code>required .com.netty.example.server.proto.ActionType actionType = 2;</code>
     */
    public boolean hasActionType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *动作类型
     * </pre>
     *
     * <code>required .com.netty.example.server.proto.ActionType actionType = 2;</code>
     */
    public com.netty.example.server.proto.TaskMessageOuterClass.ActionType getActionType() {
      com.netty.example.server.proto.TaskMessageOuterClass.ActionType result = com.netty.example.server.proto.TaskMessageOuterClass.ActionType.valueOf(actionType_);
      return result == null ? com.netty.example.server.proto.TaskMessageOuterClass.ActionType.NEW : result;
    }

    public static final int TASKIDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> taskIds_;
    /**
     * <pre>
     *任务id 列表
     * </pre>
     *
     * <code>repeated int64 taskIds = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getTaskIdsList() {
      return taskIds_;
    }
    /**
     * <pre>
     *任务id 列表
     * </pre>
     *
     * <code>repeated int64 taskIds = 3;</code>
     */
    public int getTaskIdsCount() {
      return taskIds_.size();
    }
    /**
     * <pre>
     *任务id 列表
     * </pre>
     *
     * <code>repeated int64 taskIds = 3;</code>
     */
    public long getTaskIds(int index) {
      return taskIds_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTarget()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, target_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, actionType_);
      }
      for (int i = 0; i < taskIds_.size(); i++) {
        output.writeInt64(3, taskIds_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, target_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, actionType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < taskIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(taskIds_.get(i));
        }
        size += dataSize;
        size += 1 * getTaskIdsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage)) {
        return super.equals(obj);
      }
      com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage other = (com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage) obj;

      boolean result = true;
      result = result && (hasTarget() == other.hasTarget());
      if (hasTarget()) {
        result = result && getTarget()
            .equals(other.getTarget());
      }
      result = result && (hasActionType() == other.hasActionType());
      if (hasActionType()) {
        result = result && actionType_ == other.actionType_;
      }
      result = result && getTaskIdsList()
          .equals(other.getTaskIdsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTarget()) {
        hash = (37 * hash) + TARGET_FIELD_NUMBER;
        hash = (53 * hash) + getTarget().hashCode();
      }
      if (hasActionType()) {
        hash = (37 * hash) + ACTIONTYPE_FIELD_NUMBER;
        hash = (53 * hash) + actionType_;
      }
      if (getTaskIdsCount() > 0) {
        hash = (37 * hash) + TASKIDS_FIELD_NUMBER;
        hash = (53 * hash) + getTaskIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *任务消息
     * </pre>
     *
     * Protobuf type {@code com.netty.example.server.proto.TaskMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.netty.example.server.proto.TaskMessage)
        com.netty.example.server.proto.TaskMessageOuterClass.TaskMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.example.server.proto.TaskMessageOuterClass.internal_static_com_netty_example_server_proto_TaskMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.example.server.proto.TaskMessageOuterClass.internal_static_com_netty_example_server_proto_TaskMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage.class, com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage.Builder.class);
      }

      // Construct using com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        actionType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        taskIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.example.server.proto.TaskMessageOuterClass.internal_static_com_netty_example_server_proto_TaskMessage_descriptor;
      }

      public com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage getDefaultInstanceForType() {
        return com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage.getDefaultInstance();
      }

      public com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage build() {
        com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage buildPartial() {
        com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage result = new com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.actionType_ = actionType_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          taskIds_ = java.util.Collections.unmodifiableList(taskIds_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.taskIds_ = taskIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage) {
          return mergeFrom((com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage other) {
        if (other == com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage.getDefaultInstance()) return this;
        if (other.hasTarget()) {
          bitField0_ |= 0x00000001;
          target_ = other.target_;
          onChanged();
        }
        if (other.hasActionType()) {
          setActionType(other.getActionType());
        }
        if (!other.taskIds_.isEmpty()) {
          if (taskIds_.isEmpty()) {
            taskIds_ = other.taskIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTaskIdsIsMutable();
            taskIds_.addAll(other.taskIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTarget()) {
          return false;
        }
        if (!hasActionType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object target_ = "";
      /**
       * <pre>
       *目标设备
       * </pre>
       *
       * <code>required string target = 1;</code>
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *目标设备
       * </pre>
       *
       * <code>required string target = 1;</code>
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目标设备
       * </pre>
       *
       * <code>required string target = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目标设备
       * </pre>
       *
       * <code>required string target = 1;</code>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标设备
       * </pre>
       *
       * <code>required string target = 1;</code>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000001);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标设备
       * </pre>
       *
       * <code>required string target = 1;</code>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        target_ = value;
        onChanged();
        return this;
      }

      private int actionType_ = 1;
      /**
       * <pre>
       *动作类型
       * </pre>
       *
       * <code>required .com.netty.example.server.proto.ActionType actionType = 2;</code>
       */
      public boolean hasActionType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *动作类型
       * </pre>
       *
       * <code>required .com.netty.example.server.proto.ActionType actionType = 2;</code>
       */
      public com.netty.example.server.proto.TaskMessageOuterClass.ActionType getActionType() {
        com.netty.example.server.proto.TaskMessageOuterClass.ActionType result = com.netty.example.server.proto.TaskMessageOuterClass.ActionType.valueOf(actionType_);
        return result == null ? com.netty.example.server.proto.TaskMessageOuterClass.ActionType.NEW : result;
      }
      /**
       * <pre>
       *动作类型
       * </pre>
       *
       * <code>required .com.netty.example.server.proto.ActionType actionType = 2;</code>
       */
      public Builder setActionType(com.netty.example.server.proto.TaskMessageOuterClass.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        actionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *动作类型
       * </pre>
       *
       * <code>required .com.netty.example.server.proto.ActionType actionType = 2;</code>
       */
      public Builder clearActionType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        actionType_ = 1;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> taskIds_ = java.util.Collections.emptyList();
      private void ensureTaskIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          taskIds_ = new java.util.ArrayList<java.lang.Long>(taskIds_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       *任务id 列表
       * </pre>
       *
       * <code>repeated int64 taskIds = 3;</code>
       */
      public java.util.List<java.lang.Long>
          getTaskIdsList() {
        return java.util.Collections.unmodifiableList(taskIds_);
      }
      /**
       * <pre>
       *任务id 列表
       * </pre>
       *
       * <code>repeated int64 taskIds = 3;</code>
       */
      public int getTaskIdsCount() {
        return taskIds_.size();
      }
      /**
       * <pre>
       *任务id 列表
       * </pre>
       *
       * <code>repeated int64 taskIds = 3;</code>
       */
      public long getTaskIds(int index) {
        return taskIds_.get(index);
      }
      /**
       * <pre>
       *任务id 列表
       * </pre>
       *
       * <code>repeated int64 taskIds = 3;</code>
       */
      public Builder setTaskIds(
          int index, long value) {
        ensureTaskIdsIsMutable();
        taskIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *任务id 列表
       * </pre>
       *
       * <code>repeated int64 taskIds = 3;</code>
       */
      public Builder addTaskIds(long value) {
        ensureTaskIdsIsMutable();
        taskIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *任务id 列表
       * </pre>
       *
       * <code>repeated int64 taskIds = 3;</code>
       */
      public Builder addAllTaskIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureTaskIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, taskIds_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *任务id 列表
       * </pre>
       *
       * <code>repeated int64 taskIds = 3;</code>
       */
      public Builder clearTaskIds() {
        taskIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.netty.example.server.proto.TaskMessage)
    }

    // @@protoc_insertion_point(class_scope:com.netty.example.server.proto.TaskMessage)
    private static final com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage();
    }

    public static com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TaskMessage>
        PARSER = new com.google.protobuf.AbstractParser<TaskMessage>() {
      public TaskMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskMessage> getParserForType() {
      return PARSER;
    }

    public com.netty.example.server.proto.TaskMessageOuterClass.TaskMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_example_server_proto_TaskMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_example_server_proto_TaskMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022task-message.proto\022\036com.netty.example." +
      "server.proto\"n\n\013TaskMessage\022\016\n\006target\030\001 " +
      "\002(\t\022>\n\nactionType\030\002 \002(\0162*.com.netty.exam" +
      "ple.server.proto.ActionType\022\017\n\007taskIds\030\003" +
      " \003(\003*B\n\nActionType\022\007\n\003NEW\020\001\022\t\n\005START\020\002\022\010" +
      "\n\004STOP\020\003\022\n\n\006REMOVE\020\006\022\n\n\006UPDATE\020\007"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_netty_example_server_proto_TaskMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_netty_example_server_proto_TaskMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_example_server_proto_TaskMessage_descriptor,
        new java.lang.String[] { "Target", "ActionType", "TaskIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
