spring:
  application:
    name: signalling-server



rocketmq:
  name-server: 117.50.68.180:9876


signalling:
  server:
    port: 19999
  #  name-server: 117.50.68.180:9876
  rocketmq:
    task-topic: task-topic

logging:
  level:
    test: debug
    com:
      netty:
        example: debug